Add 'packaging' dep to 'pyinstaller' testenv
Without this, frozen binaries will fail with "allmydata.PackagingError
ImportError: for requirement 'setuptools >= 28.8.0': (<type
'exceptions.ImportError'>, "The 'packaging' package is required;
normally this is bundled with this package so if you get this warning,
consult the packager of your distribution.""