Use io.open() instead of builtin open()
Windows does not like when we open README.rst using builtin open():

  Traceback (most recent call last):
    File "setup.py", line 360, in <module>
      long_description=open('README.rst', 'rU').read(),
    File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1720: character maps to <undefined>